---
version: "3.7"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    env_file:
      - pihole.env
    volumes:
      - "pihole_data:/etc/pihole/"
      - "dnsmasq_data:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 1.1.1.3
    restart: unless-stopped

volumes:
  pihole_data:
  dnsmasq_data:
